### ISSUE TITLE
stops to balance when its more then 12 players

### ISSUE THREAD

**Issue by AWJoki** [Mesharsky/CS2-Advanced-TeamBalance#1]
Hello there :)
it seams that the plugin stops to work when u reach a play amount over 12-14 it stops to balance and only says no need for balanace .. 
else it looks to works very well

**Comment by Mesharsky** [comment]
Mhmmm, weird.
Did not see that problem at all when having over 20+ players on my servers.

Can you post your config and tell me debug logs?

**Comment by AWJoki** [comment]
Hi again..
tnx for quick respond.. the config for the plugin is in default nothing is changed.. what else of config you wish to see? also i am working but i will collect debug outputs in the end of the weekend.. couse for the moment i am not home.. 
btw it has not with what type of game mode / type  u run  with that ment casual, competive or wingman ?

I could reach the outputs from log files.. 
also in the bottom you see the winning team has 11-0

also i removerd the steam ids in the post
 
[Team Balance] Evaluating if teams need to be rebalanced or scrambled...
[Team Balance] Updating player teams in cache...
[Team Balance] No balance required. Teams are balanced.
"Alaster<0><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"fiskfågel<1><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"-((EAGLES))- ADEPT<2><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"KARLSSON 1<3><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"Haakis<4><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"Skugan<5><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"Äcklet62+<6><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"Hans Höghet<7><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"Pintuz<8><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"Kurama<9><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"Dykarfröken Ellen<10><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"Pippilainen<11><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"-((EAGLES))- //Jazseeh//<12><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"J@ger<13><[U]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 
"-((EAGLES))- -=Joki=-<14><[U]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 828.45 
"-=EaglesGamingTV=-<15><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 828.45 
"-((EAGLES))- ¤>Farsan<¤<18><[U]><Spectator>" OnPreResetRound => CTMDBG, team 1  will switch 0 828.45 
"Glontan<19><STEAM_ID_PENDING><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 828.45 

Using spawn points configuration 0x5A06A76F
L 09/29/2024 - 20:40:08: Starting Freeze period
L 09/29/2024 - 20:40:08: JSON_BEGIN{
L 09/29/2024 - 20:40:08: "name": "round_stats",
L 09/29/2024 - 20:40:08: "round_number" : "12",
L 09/29/2024 - 20:40:08: "score_t" : "0",
L 09/29/2024 - 20:40:08: "score_ct" : "11",
L 09/29/2024 - 20:40:08: "map" : "de_cache",
